export const typingPassages = [
  "The impact of climate change on our planet is becoming increasingly evident. Rising global temperatures, extreme weather events, and melting ice caps are pressing concerns that demand urgent attention and concerted efforts to mitigate their effects. Governments, businesses, and individuals all have a role in reducing emissions and protecting vulnerable communities.",
  "Success in the IELTS exam comes from regular practice, careful time management, and clear communication. Building a steady routine helps learners develop confidence in every part of the test. Reviewing mistakes after each practice session is an effective way to identify weaknesses and set clear goals.",
  "Technology has transformed the way people learn, work, and stay connected. Used thoughtfully, digital tools can make knowledge more accessible and help communities solve complex problems. However, people must also develop the skills needed to evaluate information carefully and protect their privacy online.",
  "Maintaining a balanced diet and regular exercise are important parts of a healthy lifestyle. Small, sustainable choices can improve wellbeing and support long-term goals. For many people, preparing simple meals and taking a daily walk are realistic habits that gradually make a difference.",
  "Travel broadens perspectives by introducing people to new cultures, landscapes, and ideas. Meaningful experiences often begin with curiosity and respect for local communities. Visitors can make a positive contribution by supporting local businesses and learning about the customs of the place they visit.",
  "Public libraries offer more than books. They provide quiet places to study, free access to information, and activities that bring people of different ages together. As services become increasingly digital, libraries also help visitors develop practical skills for work, study, and everyday life.",
  "Many cities are encouraging residents to use bicycles and public transport. These choices can reduce traffic congestion, improve air quality, and make urban areas more pleasant. Safe cycle lanes and reliable bus services are particularly important when governments want more people to change their travel habits.",
  "Learning a new language requires patience because progress is often gradual. Listening carefully, practising regularly, and accepting mistakes are all valuable parts of the process. Conversations with other learners can be especially useful because they make new vocabulary feel more natural and memorable.",
  "Scientists study the oceans to better understand weather patterns, marine life, and the effects of pollution. Protecting these ecosystems is essential for the health of the planet. Reducing plastic waste and supporting sustainable fishing practices can help preserve ocean habitats for future generations.",
  "Remote work has changed how many organisations operate. While it gives employees more flexibility, it also requires clear communication and thoughtful ways of building teamwork. Regular check-ins and shared expectations can help colleagues remain connected even when they live far apart.",
  "Young children learn through play as they explore ideas, solve simple problems, and develop social skills. Safe outdoor spaces can make these experiences even more rewarding. Parents and teachers can encourage curiosity by providing materials that allow children to create, question, and experiment.",
  "Renewable energy sources such as solar and wind power are becoming more affordable. Investment in cleaner technology can help countries meet growing energy needs responsibly. A successful transition also depends on modern electricity networks and training opportunities for workers in new industries.",
  "Good sleep supports concentration, memory, and emotional wellbeing. Creating a calm evening routine and limiting screen time may help people rest more effectively. Even small changes, such as keeping a regular bedtime, can improve the quality of sleep over time.",
  "Museums preserve objects and stories that help visitors understand the past. Interactive exhibitions can make history more engaging for people who learn in different ways. By connecting local stories with wider events, museums can encourage visitors to think carefully about the present as well.",
  "A strong community is built when neighbours share ideas and support one another. Volunteering is one practical way to develop connections and respond to local needs. Community projects can also give people a sense of purpose while improving shared spaces and services.",
  "Urban parks provide valuable spaces where people can relax, exercise, and spend time outdoors. Trees and plants can also lower temperatures and improve air quality in busy neighbourhoods. Careful planning ensures that parks remain welcoming, safe, and accessible to everyone.",
  "Online courses allow students to learn at times and places that suit their routines. They work best when lessons include clear goals, regular feedback, and opportunities to ask questions. Many learners combine digital resources with study groups to stay motivated.",
  "Agriculture is changing as farmers use sensors, satellite images, and weather data to make better decisions. These tools can reduce waste by helping growers use water and fertiliser more efficiently. Technology is most useful when it is affordable and supported by practical training.",
  "Reading for pleasure can improve vocabulary and encourage people to see situations from different points of view. A few quiet minutes with a book each day can become a valuable habit. Schools and families can nurture this interest by making a wide range of stories available.",
  "Local markets often give small producers a chance to sell fresh food and handmade goods directly to customers. They can strengthen local economies while creating lively public spaces. Shoppers may also learn more about where products come from and how they are made.",
  "In many workplaces, mentoring helps new employees gain confidence and understand professional expectations. Experienced colleagues can share practical advice that is not always found in formal training. Both mentors and learners benefit when they set aside time for honest conversations.",
  "Wildlife conservation depends on protecting habitats as well as individual animal species. National parks, wildlife corridors, and responsible tourism can all support this goal. Local communities are more likely to support conservation when they can see clear benefits from healthy natural environments.",
  "Music is an important part of cultural life because it can preserve traditions and bring people together. Learning an instrument also develops patience, concentration, and coordination. Community performances give musicians a chance to share their skills with supportive audiences.",
  "Good design can make public buildings easier and safer for everyone to use. Features such as clear signs, step-free entrances, and comfortable waiting areas are particularly helpful. When planners listen to a diverse range of users, they can create spaces that work better for the whole community.",
  "Weather forecasts help people plan journeys, protect crops, and prepare for dangerous conditions. Modern forecasts combine observations from the ground, sea, and space to predict changes in the atmosphere. Clear communication is essential so that warnings can be understood and acted on quickly.",
  "Small businesses often build loyal customers by offering reliable service and understanding local needs. Although starting a business can involve uncertainty, careful research can reduce some of the risks. Support from advisers and other business owners can help new entrepreneurs make informed decisions.",
  "Exercise does not need to be expensive or complicated to be beneficial. Walking, swimming, dancing, and team sports can all improve physical health and reduce stress. The best activity is often one that people enjoy enough to continue doing regularly.",
  "Historic buildings give cities a distinctive character and connect residents with earlier generations. Restoring an old structure can be costly, but it may also create new homes, workplaces, or cultural venues. Successful projects balance the preservation of important details with modern safety requirements.",
  "Water is a limited resource in many parts of the world, and households can help by avoiding unnecessary waste. Fixing leaks, collecting rainwater, and choosing efficient appliances are simple actions with lasting value. Public education can encourage people to consider how their daily choices affect supply.",
  "Team sports teach people how to cooperate, communicate, and respond calmly under pressure. Winning is rewarding, but learning from a difficult match can be equally valuable. Coaches can create positive environments by recognising effort as well as individual talent.",
  "The night sky has inspired scientific discovery and human imagination for thousands of years. Today, astronomers use powerful telescopes to study distant planets and galaxies. Protecting dark skies from unnecessary light pollution makes it easier for both researchers and communities to enjoy the stars.",
  "Public art can transform ordinary streets into places that feel memorable and inviting. Murals, sculptures, and performances may reflect the history or identity of a neighbourhood. Involving residents in creative projects helps ensure that the work feels meaningful to the people who see it every day.",
  "Managing personal finances begins with understanding regular income and expenses. A simple budget can help people save for important goals and prepare for unexpected costs. Financial education is especially useful when it explains everyday decisions in clear and practical language.",
  "Food waste is a growing concern because producing food requires land, water, energy, and labour. Planning meals, storing ingredients correctly, and using leftovers creatively can reduce the amount thrown away at home. Businesses can also donate safe surplus food to organisations that support people in need.",
  "Research shows that taking short breaks can help people maintain focus during demanding tasks. Stepping away from a screen, stretching, or looking outside may give the mind time to recover. A balanced schedule should include periods of concentrated work as well as opportunities for rest.",
] as const;

export function getRandomTypingPassage(previousPassage?: string) {
  const availablePassages = previousPassage
    ? typingPassages.filter((passage) => passage !== previousPassage)
    : typingPassages;
  const passages = availablePassages.length ? availablePassages : typingPassages;

  return passages[Math.floor(Math.random() * passages.length)];
}
